image:
  file: .gitpod.Dockerfile
ports:
  - port: 3306
    onOpen: ignore
  - port: 8001
    onOpen: open-preview
    
tasks:
  - name: setup
    init: |
      npm install --save-dev browser-sync webpack-cli browser-sync-webpack-plugin
  - openMode: split-right
    command: >
      apachectl start && ./node_modules/.bin/webpack --watch