image:
  file: .gitpod.Dockerfile
ports:
  - port: 3306
    onOpen: ignore
  - port: 8001
    onOpen: open-preview
    
tasks:
  - name: setup
    init: npm install browser-sync --save-dev
    command: >
      apachectl start &&
      gp open public/index.php
