image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
    
tasks:
  - name: Apache
    command: >
      apachectl start;
  - command: >
      gp open public/index.php;gp preview $(gp url 8001);
    
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client