image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
checkoutLocation: "lamp"
workspaceLocation: "."
tasks:
  - name: Apache
    command: >
      apachectl start;
  - name: Lamp
    command: >
      chmod GITPOD_REPO_ROOT/.htaccess;
      cd $GITPOD_REPO_ROOT;
